### ISSUE TITLE
Convert Integration tests into Kotlin

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#10]

**Comment by pjhampton** [comment]
I can take this one if it's still free @sendilkumarn

**Comment by thodorisbais** [comment]
I can also help you @pjhampton with that.

**Comment by pjhampton** [comment]
Oh nice. Thanks @thodorisbais! I will ping you for a review then :+1:

**Comment by thodorisbais** [comment]
I actually meant we could split the work for this one. Sendil is the one who will review it in the end :)

**Comment by pjhampton** [comment]
I see, thanks for the offer @thodorisbais. It's pretty straight forward, but if I see opportunity for collaboration I will reach out :100:

**Comment by sendilkumarn** [comment]
Closing this for now. But feel free to work on this, if interested.
