### ISSUE TITLE
No docs for entity generation

### ISSUE THREAD

**Issue by julillosamaral** [jhipster/jhipster-kotlin#113]
No Documentation provided on how to use the tool
I started using jhipster-kotlin and managed to create the app with the data in the Readme page, when I wanted to generate a new entity I did but it was generated as Java. Searching on the issues I saw that the entities are generated as Kotlin and the issue is closed, but no documentation on how to do it is provided.

Related issues: https://github.com/jhipster/jhipster-kotlin/issues/45
JHipster Version(s) 5

[ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
@julillosamaral While the entity generator + more are done in current master they are not included in the the latest 0.7.0 release. If you want to test it out you will need to follow the [contributing guidelines](https://github.com/jhipster/jhipster-kotlin/blob/master/CONTRIBUTING.md) to build jhipster-kotlin locally and build/link with [jhipster 6.0.0-beta](https://github.com/jhipster/generator-jhipster/tree/v6.0.0-beta.0)

**Comment by julillosamaral** [comment]
Ok, I thought it was already done! Is there an estimate release date for the feature?

Thanks a lot!

**Comment by pvliss** [comment]
It is done, just not released yet :) . I am sorry but being open source we can not give any dates. We would highly appreciate any feedback though :). 

To make the instructions a bit simpler here's what you need to do to test it out:
```bash
# 1. Install JHipster 6.0.0.beta and verify
$ npm install -g generator-jhipster@beta
$ jhipster --version
# 2. Clone jhipster-kotlin, install and link it
$ git clone https://github.com/jhipster/jhipster-kotlin
$ cd jhipster-kotlin
$ npm install && npm link
# 3. Create new project dir and link jhipster-kotlin
$ cd .. 
$ mkdir khipster-app && cd khipster-app 
$ npm link generator-jhipster-kotlin
# 4. Generate a new app
$ jhipster --blueprint kotlin
```

**Comment by sendilkumarn** [comment]
We do have `khipster` available now for installing things. I think this issue can be close. Please feel free to re-open if you think we are still missing something.
Check out the commit    db5f579d0298d134d23c46186045a7a6e9695801
