### ISSUE TITLE
Update to JHipster 6.0.1 final

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#116]
Update to final 6.0.0 release of JHipster.

**Comment by pvliss** [comment]
@sendilkumarn We are currently synced with 6.0.0.beta and should sync to the final release. I have been meaning to get to this for some time but did not have the time. Have you done any work  on this or should I start updating? Also do you think we should wait for 6.0.1 or would it be easier to have them in separate PRs(as there are a lot of fixes/changes for 6.0.1 as well)?

**Comment by sendilkumarn** [comment]
We will do it separately. I want to release 1.0.0 this before the end of May. 

I did not do anything for 6.0.0 yet. If you havent start anything, I will start something soon

**Comment by pvliss** [comment]
No I haven't. Been busy lately, sorry.

**Comment by sendilkumarn** [comment]
Cool no worries. I will have a look 👍

**Comment by sendilkumarn** [comment]
Closed #114
