### ISSUE TITLE
Use the JHipster release instead of master in CI

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#118]
Currently, we are using JHipster's master branch as the base when testing in the CI.

Instead use JHipster release version for testing the CI. This will make the build more stable.

cc: @pascalgrimaud this is might be something that interests you ❤️

**Comment by pascalgrimaud** [comment]
Yes, switch this value to `release` should normally work (I hope !!):
https://github.com/jhipster/jhipster-kotlin/blob/master/.travis.yml#L46-L48

**Comment by pvliss** [comment]
It seems that we cannot use release without also altering the copying part as we re-use the test scripts and examples(more specifically `$JHI_HOME` should be set appropriately). But I think it is better to build against the specific version we support as future releases of JHipster could also potentially brake the build. @sendilkumarn  + @pascalgrimaud What do you think?
