### ISSUE TITLE
Move to Java 11 for Travis and Azure build

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#119]
Refer https://github.com/jhipster/generator-jhipster/pull/9539

**Comment by pvliss** [comment]
@sendilkumarn I see you added the `good first issue` label but I do not see anyone interested in doing a PR so thinking of doing one. Do you think we should wait a bit more? Also are you planning to make a beta release soon as I believe most of the work has been done and we could really use some feedback?

**Comment by sendilkumarn** [comment]
We can do it 👍
