### ISSUE TITLE
Question/FeatureRequest Kotlin beside Java

### ISSUE THREAD

**Issue by unknowedNp** [jhipster/jhipster-kotlin#121]
Can have kotlin source and java togather ?
write some class with kotlin and other class with java

**Comment by pvliss** [comment]
@unknowedNp Yes, definitely!!! While KHipster now generates only Kotlin code the generated project supports mixing Java and Kotlin code for both Maven and Gradle builds. You only need to add directory `src/main/java` (or `src/test/java`) and it should work out of the box.

**Comment by unknowedNp** [comment]
oh, thats awesome
can use kotlin in exisiting jhipster project ?

**Comment by sendilkumarn** [comment]
@unknowedNp You need to add in extra configurations (manually) to `maven` or `gradle` that compiles Kotlin. If you want to use it in an existing project.
