### ISSUE TITLE
Messages are duplicated

### ISSUE THREAD

**Issue by amatosg** [jhipster/jhipster-kotlin#123]
## Overview of the issue
Running `khipster entity Category` will show the questions twice, like this:

 ![](https://framapic.org/NPs7JXo2TJME/H5kFmn2V6Ocj)

This also happens when a user is asked if file should be overridden or ignored.

## Motivation for or Use Case
I think this is self-explanatory.

## Reproduce the error
Run `khipster entity Category` or simply `khipster` in an existant project.

## Related issues
None
## JHipster Version(s)
0.8.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by amatosg** [comment]
this also happens when running `khipster --import-jdl file.jh`

**Comment by pvliss** [comment]
@sendilkumarn I believe PR #126 fixes this issue of duplicate invocations.

@amatosg As a workaround you can also replace `khipster` with `jhipster --blueprint kotlin`
