### ISSUE TITLE
Issue template is missing come chars

### ISSUE THREAD

**Issue by amatosg** [jhipster/jhipster-kotlin#124]
## Overview of the issue
1. Each element in the template should start with `##`
2. The check at the end of the ticket should be `-[ ]` so it will be rendered as a checkbox
## Motivation for or Use Case
It makes the final issue more readable
## Reproduce the error
Does not apply
## Related issues
None
## Link to PR (if any)
None
## JHipster Version(s)
Does not apply
-[ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Done this. Thanks for raising this issue. 👍 
6f2ce1b5b7e06e5da74e875b12d42355c1c7fc4c
