### ISSUE TITLE
JDL import doesn't import entities

### ISSUE THREAD

**Issue by amatosg** [jhipster/jhipster-kotlin#125]
## Overview of the issue
when running `khipster --import-jdl file.jh` entities are not imported and messages are duplicated (as in #123).

A workaround is to copy an existing .jhipster folder and run `khipster --with-entities`

## Motivation for or Use Case
This feature should work as expected ;)

## Reproduce the error
Just run the command :)

## Related issues
#123 

## Link to PR (if any)
None yet

## JHipster Version(s)
0.8.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
The duplicate issue is fixed in the master.

Sometimes I notice when there is a `.jhipster` folder exists already, the import command does not work as expected. Try deleting the `.jhipster` folder and re-run the generation.

**Comment by amatosg** [comment]
there was no folder before I ran the import which lead to the error, when I pasted the whole folder it worked.

**Comment by sendilkumarn** [comment]
This is interesting. We will have to investigate this one. Can you share your `file.jdl`

**Comment by amatosg** [comment]
Sorry, I was on vacation. Have you tried with the vanilla jdl from JDL Studio?

**Comment by plank-tools** [comment]
@amatosg I'm sure the vanilla jdl is pretty well-tested.

**Comment by amatosg** [comment]
@plank-tools did **you** tried?

**Comment by pvliss** [comment]
@amatosg I just checked and I can not reproduce the problem. I think it has been solved with #126 which is available since 0.8.1. BTW, the proper command is `khipster import-jdl file.jh` (note the missing `--`). Can you please give another try and let us know if you still face the same issue?

**Comment by amatosg** [comment]
@pvliss yeap, you are correct, this is working properly as of 0.8.1 :)

**Comment by pvliss** [comment]
@amatosg Great!!! Thanks for the update
