### ISSUE TITLE
Configure Sonar to inspect Kotlin source code

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#130]
## Overview of the issue
Currently no static code analysis is performed for the generated Kotlin code. We can use [detekt](https://github.com/arturbosch/detekt) along with https://github.com/arturbosch/sonar-kotlin

## Motivation for or Use Case
Perform static code analysis and add reports to Sonar

## JHipster Version(s)
6.0.1

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
That is really a great idea. We should do this.
