### ISSUE TITLE
Misstype in UserFeignClientInterceptor

### ISSUE THREAD

**Issue by Rotenkampf** [jhipster/jhipster-kotlin#135]
## Overview of the issue
Misstype in Kotlin code of UserFeignClientInterceptor
## Motivation for or Use Case
Use AuthorizedUserFeignClient
## Reproduce the error
1. Create microservice architecture with at least one microservice excepting gateway and UAA
2. Create interface annotated with AuthorizedUserFeignClient
3. Create any method in this interface
4. Call it somehow
5. Get 401 http code
6. Profit!
## JHipster Version(s)
6.0.1
- [ *] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
@Rotenkampf Thanks for reporting this. Will have a look at it hopefully tomorrow. In the meantime, in order to help us reproduce and fix the problem faster, you could run `jhipster info` for your generated apps and paste the results here.

**Comment by pvliss** [comment]
@Rotenkampf Also if you know already have a fix for this then PRs are welcome!!!

**Comment by Rotenkampf** [comment]
Just created PR https://github.com/jhipster/jhipster-kotlin/pull/136
