### ISSUE TITLE
Convert usages of Optional to Kotlin built-in null safety features

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#139]
## Overview of the issue
Convert usage of Java's `Optional` to the Kotlin built-in null safety features.

## Motivation for or Use Case
As the bulk of the Java code is now migrated to Kotlin we can start fully migrating to Kotlin using more of its built-in features. This might seem as it should have been done already but it was intentionally left out to ease the process of migration(#85) and made the sync with parent JHipster project easier and faster. Doing this will definitely make the sync a bit harder but it is worth the effort as it will produce proper and easier to read Kotlin code.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kozub** [comment]
Hello Team,

I've started working on that issue. It looks that there are 19 Kotlin classes that produces / uses Optional + classes that consumes producer code. 

I've started with classes that are generated for now simple microservice which contains 6 classes with Optionals. I will create PR soon to show that changes.

**Comment by julillosamaral** [comment]
Is there a way I can help with this?

**Comment by sendilkumarn** [comment]
closing this. Since this will be handled in the new releases.
