### ISSUE TITLE
Upgrade to JHipster 6.1.2

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#141]
## Overview of the issue

Upgrade to [JHipster 6.1.2](https://www.jhipster.tech/2019/06/23/jhipster-release-6.1.2.html). 

[Changes from 6.1.2](https://github.com/jhipster/generator-jhipster/compare/v6.0.1..v6.1.2)

## JHipster Version(s)
6.1.2
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
Will start working on this

**Comment by pvliss** [comment]
Although as there will be a new version coming soon will update both in one pass and update the title and description accordingly

**Comment by sendilkumarn** [comment]
Awesome @pvliss 👍 

I guess there is also 1.3.40 released.

**Comment by pvliss** [comment]
Yes there is a new release. Would you like me to make a PR for it? If so, we could also make a new release including #152. WDYT?

**Comment by sendilkumarn** [comment]
Sure @pvliss 

I created a ticket for Kotlin upgrade #154

**Comment by pvliss** [comment]
Thanks @sendilkumarn
