### ISSUE TITLE
Use @Suppress("unused") instead of @SuppressWarnings("unused") in generated repositories

### ISSUE THREAD

**Issue by andre-stefanov** [jhipster/jhipster-kotlin#143]
## Overview of the issue
At the moment generated repositories use @SuppressWarnings annotations to suppress unused function warnings. [@Suppress](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-suppress/index.html) should be used instead.

```kotlin
// now
@SuppressWarnings("unused")
@Repository
interface EventRepository : JpaRepository<Event, Long> {
}
````
```kotlin
// should be
@Suppress("unused")
@Repository
interface EventRepository : JpaRepository<Event, Long> {
}
````
## Motivation for or Use Case
Using the correct annotation would reduce lint warning count of the generated project.
## Reproduce the error
Create a new entity by executing `jhipster entity EntityName`
## JHipster Version(s)
generator-jhipster-kotlin@0.8.1
generator-jhipster@6.0.1
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
Thanks for reporting @andre-stefanov and you are absolutely right!!! Would you be interested in submitting a PR?
