### ISSUE TITLE
Use single expression functions 

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#153]
## Overview of the issue
Use [single expression functions](https://kotlinlang.org/docs/reference/functions.html#single-expression-functions) where possible

## Motivation for or Use Case
Simplify generated code

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
@sendilkumarn This should also be fairly simple. Can you add some labels here as well as I am not allowed to add them?

**Comment by sendilkumarn** [comment]
I love this and it makes the code concise 👍

**Comment by sendilkumarn** [comment]
@pvliss done that just now

**Comment by pvliss** [comment]
@sendilkumarn I agree and thanks

**Comment by pvliss** [comment]
Going to start working on this one
