### ISSUE TITLE
Declare utility functions as top level

### ISSUE THREAD

**Issue by leonardortlima** [jhipster/jhipster-kotlin#161]
## Overview of the issue

Declare utility functions, like the ones in `DefaultProfileUtil` and `RandomUtil` as [top level functions](https://kotlinlang.org/docs/reference/functions.html#function-scope)

## Motivation for or Use Case

It is the [recommended practice](https://discuss.kotlinlang.org/t/best-practices-for-top-level-declarations/2198) for such cases  to always use top-level when possible.

The files could be annotated with `@file:jvmName` to help with Java interoperability.

**Comment by pvliss** [comment]
@leonardortlima Thanks for the suggestion. Majority of this work has been done already in master(have a look at #138) but has not been release yet. will be available on the next version. What has not been done though is using `@file:jvmName` and also the main application class. Would you be interested in submitting a PR?

**Comment by leonardortlima** [comment]
Sure, I'd be happy to help!

**Comment by pvliss** [comment]
Great, thanks!!! Let us know if you need any help

**Comment by leonardortlima** [comment]
I opened #163 which covers the utility classes.

I was playing around with making main top level too:

- Simply making `main` top level does not work; It is not longer picked up by maven / gradle because the main class name would be different.

- Adding `@file:JvmName` won't work because the class ends up being duplicated. 

One possible solution is to change the main class name in gradle, maven and in entrypoint.sh, but I have no idea how to do that.

**Comment by pvliss** [comment]
> One possible solution is to change the main class name in gradle, maven and in entrypoint.sh, but I have no idea how to do that.

This is also the reason why I left it out initially and that would probably require a lot of changes in the code of the base generator to do it properly or during generation to find and replace the main within the required files(but feels hackish to me).  The other alternative would be to keep the `@file:JvmName` using the `<%= mainClass %>` name and rename the actual class within the file to something else. But again this would need changes all over. I believe that currently this is not worth the effort. @sendilkumarn WDYT?

**Comment by sendilkumarn** [comment]
I do feel the same.  I would be very interested to see what Kotlin community is advocating for Spring... Might be a good candidate to discuss with them too.

**Comment by sendilkumarn** [comment]
This will need a lot of changes (or hacks) in the sub-generator. We will close this. When the main generator supports these kind of changes we will add this in future. Feel free to re-open the issue, if you feel otherwise.
