### ISSUE TITLE
Gateway app

### ISSUE THREAD

**Issue by Oleg25** [jhipster/jhipster-kotlin#162]
Hello. Ple I just generate new project (gateway app with uaa) and start it after some seconds i've got this error

Same project in java works fine

i have consul an uaa(jhipster)

![image](https://user-images.githubusercontent.com/2542786/60173250-f7773d00-9816-11e9-8808-ccee753e656f.png)

   : UT005023: Exception handling request to /management/health

java.lang.IllegalStateException: super.extractToken(request) must not be null

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster-kotlin": {
    "promptValues": {
      "packageName": "com.lorusscm.infra.gateway"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.lorusscm.infra.gateway",
    "packageFolder": "com/lorusscm/infra/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false
  },
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "ru"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "clientFramework": "angularX",
    "clientTheme": "materia",
    "clientThemeVariant": "dark",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "0.8.1"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": [
      "ru",
      "en"
    ],
    "blueprint": "generator-jhipster-kotlin",
    "blueprintVersion": "0.8.1"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.17.1

node: v10.16.0

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.16.0

Docker version 18.09.6, build 481bc77

docker-compose version 1.24.0, build 0aa59064

**Comment by pvliss** [comment]
@Oleg25 Thanks for reporting. I believe this is fixed in master(see #137). Until a new version is release can you try changing the return type of `CookieTokenExtractor.extractToken` to `String?`. See here for full `CookieTokenExtractor`:
``` kotlin
/**
 * Extracts the access token from a cookie.
 * Falls back to a [BearerTokenExtractor] extracting information from the Authorization header, if no
 * cookie was found.
 */
class CookieTokenExtractor : BearerTokenExtractor() {
    /**
     * Extract the JWT access token from the request, if present.
     * If not, then it falls back to the [BearerTokenExtractor] behaviour.
     *
     * @param request the request containing the cookies.
     * @return the extracted JWT token; or `null`.
     */
    override fun extractToken(request: HttpServletRequest): String? {
        val accessTokenCookie = OAuth2CookieHelper.getAccessTokenCookie(request)
        return if (accessTokenCookie != null) {
            accessTokenCookie.value
        } else {
            super.extractToken(request)
        }
    }

}
```

**Comment by Oleg25** [comment]
Thank u

**Comment by sendilkumarn** [comment]
@Oleg25 Did you re-opened it accidentally

**Comment by Oleg25** [comment]
> @Oleg25 Did you re-opened it accidentally?

Yes i did, sorry
