### ISSUE TITLE
Add documentation for testing master

### ISSUE THREAD

**Issue by amatosg** [jhipster/jhipster-kotlin#176]
## Overview of the issue
At the moment there are (maybe) many features in master that hasn't been released yet and could not be tested
## Motivation for or Use Case
The documentation should include steps to test the master branch, this will increase `master` usage and will help find bugs faster
## Reproduce the error
Read the docs :)
## Related issues
None
## Link to PR (if any)
None
## JHipster Version(s)
None, but it should say _KHipster_, right?
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Thanks for opening the issue. The simplest way is this https://github.com/jhipster/jhipster-kotlin/pull/171#issuecomment-520898792


More detailed step is here https://github.com/jhipster/jhipster-kotlin/blob/master/CONTRIBUTING.md

**Comment by sendilkumarn** [comment]
> None, but it should say KHipster, right?

**Comment by amatosg** [comment]
> You are correct (but both are same wink). Will you be interested in PR?
I think I don't have rights to edit issue templates :disappointed:

**Comment by ruddell** [comment]
@amatosg The issue template is a file in the repository in the `.github` folder, see https://github.com/jhipster/jhipster-kotlin/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by amatosg** [comment]
one thing it's not clear (at least for me) is how do I unlink `generator-jhipster` so I don't use the master branch?

**Comment by sendilkumarn** [comment]
AFAICT you should not link it in jhipster-kotlin folder

**Comment by amatosg** [comment]
[step 3 says so](https://github.com/jhipster/jhipster-kotlin/blob/master/CONTRIBUTING.md#step-3-%EF%B8%8F--to-setup-jhipster-kotlin-generator) :confused:  :
`npm link generator-jhipster`

**Comment by sendilkumarn** [comment]
@amatosg Thanks for highlighting and sorry for the delay. Amended the contents 👍
