### ISSUE TITLE
Error running KHipster command

### ISSUE THREAD

**Issue by arabbani** [jhipster/jhipster-kotlin#179]
## Overview of the issue
Khipster is reporting that the `generator-jhipster-kotlin` is not installed while running the `khipster` command, even though `generator-jhipster-kotlin` is installed.

> I am using yarn

## Motivation for or Use Case
Here is the full cli output:
`
khipster
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: blueprints: kotlin, from-cli: true

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.2.0
Application files will be generated in folder: D:\web\Research\test\nosql
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-kotlin blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-kotlin.
    at Environment.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:176:40)
    at module.exports.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1448:18)
    at shelljs.exec (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base-private.js:839:22)
    at C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\shelljs\src\exec.js:127:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
Emitted 'error' event at:
    at Environment.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:178:15)
    at module.exports.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1448:18)
    [... lines matching original stack trace ...]
    at Pipe._handle.close (net.js:606:12)
`

## KHipster Version(s)
KHipster version: 1.1.0

- [] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
Thanks for reporting @arabbani . I believe you have hit a known issue https://github.com/jhipster/generator-jhipster/issues/10223 which has already been fixed in master of the main gnerator. As a workaround can you please try installing `generator-jhipster-kotlin` locally and see if it works?

**Comment by arabbani** [comment]
Sure @pvliss . I will try this

**Comment by liefra** [comment]
A local install with `npm i generator-jhipster-kotlin` solved the issue for me on a Mac

**Comment by xiaoguizi87** [comment]
A local install with npm i generator-jhipster-kotlin solved the issue for me on a Windows 10 pc

**Comment by arabbani** [comment]
I have upgraded to jhipster v6.3.0. Still not working

**Comment by arabbani** [comment]
Any word on this?

**Comment by sendilkumarn** [comment]
Check out the latest version and use `khipster`.  Please feel free to re-open if you still have a problem.

**Comment by arabbani** [comment]
Ok.

**Comment by arabbani** [comment]
Still not working. I have used khipster command

**Comment by sendilkumarn** [comment]
Can you please post the error log?

**Comment by arabbani** [comment]
khipster
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: blueprints: kotlin, from-cli: true


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.3.1
Application files will be generated in folder: D:\web\Research\test\tt
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-kotlin blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-kotlin.
    at Environment.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\yeoman-environment\lib\environment.js:176:40)
    at module.exports.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1464:18)
    at shelljs.exec (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base-private.js:839:22)
    at C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\shelljs\src\exec.js:121:9
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Emitted 'error' event at:
    at Environment.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\yeoman-environment\lib\environment.js:178:15)
    at module.exports.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1464:18)
    [... lines matching original stack trace ...]
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Comment by arabbani** [comment]
I'm using windows 10.

**Comment by sendilkumarn** [comment]
This is interesting. Can you try uninstalling the JHipster generator and re-install kotlin generator and try

**Comment by arabbani** [comment]
Trying. Will let you know

**Comment by arabbani** [comment]
Ok. I re-installed everything. Same problem

**Comment by arabbani** [comment]
I'm using yarn

**Comment by sendilkumarn** [comment]
Did you install generator-jhipster too? if yes, please uninstall and try. 

if no, please post the output of `khipster info`

**Comment by arabbani** [comment]
I have uninstalled generator-jhipster. Same problem.

**Comment by arabbani** [comment]
Here is the result of khipster info:

`λ khipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: blueprints: kotlin, from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
D:\web\Research\test\tt
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20190717_282 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)

git version 2.19.0.windows.1

node: v10.16.1

npm: 6.4.1

yeoman: 3.1.0

yarn: 1.19.0

INFO! Congratulations, JHipster execution is complete!`

**Comment by sendilkumarn** [comment]
Do you happen to have `JHipster-kotlin` package inside here `C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\` ?

**Comment by arabbani** [comment]
Yes

**Comment by arabbani** [comment]
Is there a problem?

**Comment by sendilkumarn** [comment]
There is no call to the generator-jhipster-kotlin in the files provided.

**Comment by arabbani** [comment]
What do i do
