### ISSUE TITLE
repository/SocialUserConnectionRepository doesn't have return types for delete functions

### ISSUE THREAD

**Issue by tharakadesilva** [jhipster/jhipster-kotlin#18]
The return type for the delete functions are only generated for databaseType === 'couchbase'. For others there are no return type(s) defined which causes the delete functions to be generated without a return type:

```
fun deleteByUserIdAndProviderId(userId: String, providerId: String):

fun deleteByUserIdAndProviderIdAndProviderUserId(userId: String, providerId: String, providerUserId: String):
```

Potential fix: should probably add an else clause to set the return type to `Void`.

**Comment by sendilkumarn** [comment]
Good catch, just to move the `:` inside the if condition
