### ISSUE TITLE
Add travis to the project 

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#2]
We can add travis to this project, to test the default cases atleast at first or else copy the same testing with what we have in the main project.

**Comment by pascalgrimaud** [comment]
another question: what is the current status of this repo ? is it working ?

**Comment by sendilkumarn** [comment]
It works for the default application with gradle.
I think we can have a simple travis build for default application alone now.

For maven there is an issue #7 the build is flaky

**Comment by sendilkumarn** [comment]
I am sure that the maven issue is because of dependencies ordering but needs investigation

**Comment by pascalgrimaud** [comment]
@jdubois : can you activate this repo in Travis plz ?

**Comment by sendilkumarn** [comment]
@jdubois done :) 

@pascalgrimaud  👍

**Comment by pascalgrimaud** [comment]
Sorry for pinging, Sendil can do it

**Comment by pascalgrimaud** [comment]
@sendilkumarn : I'm starting the work this morning but I have an issue.
If I put an existing `.yo-rc.json` in a folder and use: `jhipster --force --skip-checks --blueprint generator-jhipster-kotlin`, I have to answer the question, instead of auto generating everything.

So the Travis builds failed, because it waits for the answer:

```
Running default command
Executing jhipster:app
Options: blueprint: generator-jhipster-kotlin, force: true, insight: false, skipChecks: true, withEntities: true, skip-checks: true, with-entities: true
        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            http://www.jhipster.tech
Welcome to the JHipster Generator v4.14.0
 _______________________________________________________________________________________________________________
  If you find JHipster useful consider supporting our collective https://opencollective.com/generator-jhipster
  Documentation for creating an application: http://www.jhipster.tech/creating-an-app/
 _______________________________________________________________________________________________________________
Application files will be generated in folder: /home/travis/app
? What is your default Java package name? (com.mycompany.myapp) 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by sendilkumarn** [comment]
`{
  "generator-jhipster-kotlin": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "3fd8caed5ff1f00d9337f02f59b3edecd443dcf8",
    "enableTranslation": true
  },
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "jhipster",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "blueprint": "generator-jhipster-kotlin"
  }
}
`

**Comment by sendilkumarn** [comment]
I think you need to have this blueprint there

**Comment by pascalgrimaud** [comment]
Oh ok thanks, I will update my branch soon

**Comment by sendilkumarn** [comment]
It is here https://travis-ci.org/jhipster/jhipster-kotlin

**Comment by pascalgrimaud** [comment]
Oh I see, it's because the link in README is incorrect

**Comment by sendilkumarn** [comment]
@pascalgrimaud updated
