### ISSUE TITLE
Enable GitHub actions CI

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#203]
## Overview of the issue
Currently the CI is setup only with Travis and Azure, we should use GitHub actions.

## Motivation for or Use Case

Better and Faster CI

## Reproduce the error
NA 

## Related issues
NA

## Link to PR (if any)
NA

## KHipster Version(s)
NA
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@sendilkumarn, let me know if you need help here. I can spend some time over weekend.

**Comment by sendilkumarn** [comment]
@vishal423 please feel free to take this. Thanks 🙂
