### ISSUE TITLE
Regenerate creates Java app

### ISSUE THREAD

**Issue by jgrgt** [jhipster/jhipster-kotlin#204]
## Overview of the issue
First generate your project using the kotlin (and vue) blueprint. Then change authenticationType to 'session' in .yo-rc and run 'jhipster' again. This generates a bunch of new Java files instead of (re)genating the kotlin files. (This includes the 'app' file.)
## Motivation for or Use Case
I want to switch to a different authentication type.
## Reproduce the error
See overview.
## KHipster Version(s)
1.3.0, JHipster version 6.4.1

- [] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Thanks @jgrgt for raising the issue. I too recently saw this happening, but in my case I was using locally linked master branch of both `K and J Hipster`


Are you using locally linked version?

**Comment by jgrgt** [comment]
Hi @sendilkumarn 
I was using JHipster releases, no local branch. I ran it like this: `jhipster app --blueprints kotlin,vuejs`

**Comment by sendilkumarn** [comment]
@jgrgt Sorry, I cannot replicate the issue (without using locally linked NPM packages). Do you have any steps or scenarios in which this happens?

**Comment by HenningThiemann** [comment]
@jgrgt : you should use khipster for regenerating

**Comment by sendilkumarn** [comment]
Closing this. @jgrgt feel free to reopen if you still have the issue.
