### ISSUE TITLE
CacheConfiguration is missing HibernatePropertiesCustomizer

### ISSUE THREAD

**Issue by rburgst** [jhipster/jhipster-kotlin#210]
## Overview of the issue

The problem is that Hibernate is not initialized with the correctly initialized CacheManager. This causes classloading issues when using spring-boot-devtools (which are VERY hard to track down).

The solution is to add 

https://github.com/jhipster/generator-jhipster/blob/d3ca4348c6289715316f1a5397af426579c0549a/generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs#L192

## Motivation for or Use Case

Create a kotlin app using caffeine cache with entities where an entity is using an enum.

## Reproduce the error

Create a kotlin app using caffeine cache with entities where an entity is using an enum.

## KHipster Version(s)

- latest (1.3.0)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
This is closed by d40a746

Thanks for raising it 👍
