### ISSUE TITLE
Are there plans to keep this alive? The Java generator has moved to v6.7.1

### ISSUE THREAD

**Issue by cristisp** [jhipster/jhipster-kotlin#216]

**Comment by sendilkumarn** [comment]
Hi @cristisp The 6.7.1 is a huge change. It will take sometime for me to change everything and do a release. I will be more than happy to accept any PRs :) 

cc: @jhipster/developers

**Comment by cristisp** [comment]
@sendilkumarn Thanks for the update - just wasn't sure if this is still in active development or not. Perhaps setting a milestone would help.

**Comment by gmarziou** [comment]
@cristisp last commit is from 2 months ago, so you should not worry too much :)

**Comment by mraible** [comment]
@sendilkumarn I'm curious. How do you update this blueprint to stay current JHipster? I'd like to help if I can.

**Comment by sendilkumarn** [comment]
Honestly I do not have a valid strategy. I first update the server template and then will update the entity templates. 

But I am thinking whether we should do a PR by PR update (matching JHIpster's PR). WDYT?

**Comment by mshima** [comment]
If I may suggest, there are 2 proposed features that may help keeping kotlin blueprint updated:
- https://github.com/jhipster/generator-jhipster/issues/11173:
This will allow to create a blueprint for additional contents. Ex every file needed by Kotlin.
- https://github.com/jhipster/generator-jhipster/pull/11337:
This is a renaming/filtering strategy.
So Its possible to ignore every file ending with '.java' or every file at folder 'src/main/java' 
But it's only implemented for client for now.

**Comment by sendilkumarn** [comment]
@mraible also we are blocked by this https://github.com/spring-projects/spring-framework/issues/20606
