### ISSUE TITLE
Add release drafter

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-kotlin#224]
Similar to https://github.com/jhipster/jhipster-vuejs/issues/507
With this, you can have this kind of release note: https://github.com/jhipster/jhipster-vuejs/releases

I'm waiting generator-jhipster@v6.9.0 and I will probably add this to main generator-jhipster too.

@sendilkumarn : would you want me to add this?

**Comment by sendilkumarn** [comment]
Awesome. We can add it. 

Also I am thinking to release the packages in the GitHub registry too. But I don't have access for that. Can you help with that?

**Comment by pascalgrimaud** [comment]
Ok, I'll work on the release drafter later

About GitHub Registry package, I don't know at all how it works.
Let's open a new ticket and I'll try to read some documentation to know how I can activate it

**Comment by pmverma** [comment]
my 2 cents.
@pascalgrimaud 
We do need to activate it. It is already available with every repository, we just need to push artifacts/packages to it and it is ready.
One minor thing with GPR is that we need to configure this custom repo in every ecosystem we want to use.
IMO using this as a secondary hosting would be better.

**Comment by pascalgrimaud** [comment]
thanks @pmverma, so I need to check @sendilkumarn's permissions

**Comment by pmverma** [comment]
@pascalgrimaud 
I missed negation operator. 
> We do need to activate it.

We do **NOT** need to activate it. 😀
