### ISSUE TITLE
GitHub Packages

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-kotlin#225]
As asked by @sendilkumarn - see https://github.com/features/packages

**Comment by mshima** [comment]
@pascalgrimaud probably package registry would fit to generator-jhipster too.
I am not sure but probably it would allow us to publish a snapshot at each commit and them trigger daily-build builds.

https://developer.github.com/v3/activity/events/types/#packageevent

**Comment by pascalgrimaud** [comment]
yes sure, I wanted to do this, but I'd prefer to "test" with some blueprint before, like jhipster-kotlin or jhipster-vuejs and if it works well, we can do the same for generator-jhipster

**Comment by sendilkumarn** [comment]
I am +1 for experimenting here 👍🎉

**Comment by pascalgrimaud** [comment]
> @pascalgrimaud probably package registry would fit to generator-jhipster too.
I am not sure, but probably it would allow us to publish a snapshot at each commit and them trigger daily-build builds.

> https://developer.github.com/v3/activity/events/types/#packageevent

Of course @mshima but I'd prefer baby steps. Let's test this with a smaller project before doing it with a big project like generator-jhipster :-D

**Comment by sendilkumarn** [comment]
Closing this issue for now. It looks like migrating to GitHub registry is not ideal at this moment.
