### ISSUE TITLE
Gradle + kotlin + liquibase diff not working

### ISSUE THREAD

**Issue by Romancha** [jhipster/jhipster-kotlin#230]
## Overview of the issue
Gradle + kotlin + liquibase diff not working as expected
## Motivation for or Use Case
I think that this should work out of the box, without additional configurations, since this kotlin-hipster
## Reproduce the error
1. Generate khipster project with gradlew
2. Start application and stop application
3. Do some changes in domain entities - add new field in existing entity or add new entity (does not matter)
4. Try to generate liquibase diff change log by command `gradlew liquibaseDiffChangeLog -PrunList=diffLogd`

**Expected result:** diff generated
**Actual result:** no changes generated

I investigated this problem a bit and found that in liquibase.activities.diffLog classpath = `classpath "$buildDir/classes/java/main"` but essentially, there are no domain entities along this path after compilation.

I found that if I generate an app with maven - problem is not reproduced, because in folder `$buildDir/classes/java/main` there are java classes compiled from kotlin.

Possibly a problem in the gradle compiler plugin...

**I found a workaround for me** - change classpath from `$buildDir/classes/java/main` to `$buildDir/classes/kotlin/main`.

But I think it doesn't look like the best solutions, but rather like a hack. Since if someone has a project java+kotlin in this case only kotlin entities will be applied. But still, this will work out of the box for 100% kotlin project.

## Related issues
n/a
## Link to PR (if any)
n/a
## KHipster Version(s)
1.6.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Thanks for the detailed issue. This is indeed a bug, we have to fix this. Would you be willing to send a PR for this?

**Comment by julillosamaral** [comment]
@sendilkumarn For the PR, changing the classpath to be `$buildDir/classes/kotlin/main` would be enough?
I think I can check it out in the next few days

**Comment by sendilkumarn** [comment]
Thanks @julillosamaral sure 🙂

**Comment by sendilkumarn** [comment]
Closing this! please feel free to reopen if this is still happening. Thanks.

**Comment by Giddu** [comment]
@Romancha , thanks for the solution. I'm using liquibase + kotlin and your suggestion fixed my issue.
