### ISSUE TITLE
"JSON conversion problem: Parameter specified as non-null is null" is thrown when trying to reference one JDL entity from another entity.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [jhipster/jhipster-kotlin#232]
## Overview of the issue

When two entities have a one-to-many relationship and you try to set the reference to the "one" entity from the "many" entity, it throws the error "JSON conversion problem: Parameter specified as non-null is null."

I'll use the example JDL configuration provided in the JDL studio for this issue in order to show that this is a widespread problem that affects even the example code. When I try to set the "Location" field in the "Department" entity, I get the following error:

    WARN [PID] --- [  XNIO-1 task-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageConversionException: JSON conversion problem: Parameter specified as non-null is null: method com.example.demo.domain.Department.setEmployees, parameter <set-?>; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Parameter specified as non-null is null: method com.example.demo.domain.Department.setEmployees, parameter <set-?> (through reference chain: com.example.demo.domain.Department["employees"])]

Weirdly enough it references the method `setEmployees`, which doesn't exist in the codebase, and I wasn't changing any of the employee database entries anyway.

Additionally, when I try to set the "Country" field on the "Location" entity, it goes through just fine, except when the Country ID has already been set for a different Location database entry, in which case it will return the following error:

    WARN [PID] --- [ XNIO-1 task-23] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [update location set city=?, country_id=?, postal_code=?, state_province=?, street_address=? where id=?]; constraint ["PUBLIC.UX_LOCATION_COUNTRY_ID_INDEX_9 ON PUBLIC.LOCATION(COUNTRY_ID) VALUES 1"; SQL statement:
     update location set city=?, country_id=?, postal_code=?, state_province=?, street_address=? where id=? [23505-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch]

## Reproduce the error
1. Create a new KHipster project (I also used the Vue.js blueprint but that probably doesn't matter)
2. Go to https://start.jhipster.tech/jdl-studio/ and download the .jh file by pressing CTRL+S
3. Import the .jh file with the jhipster command
4. Start the development server and sign with username`admin` and password `admin`
5. Click on the "entities" dropdown in the navbar, click on "Department". Then click edit on the first automatically generated example and try to set the "Location" field. Notice that the upload process never completes on the frontend. Check the JHipster log in the console and you should see the first error I mentioned.
6. Now click on the "entities" dropdown again and this time choose the "Location" entity. Set the "Country" field for the first automatically generated example then try setting the same Country ID on the second example. The console should display the second error.

## KHipster Version(s)
I used Khipster version 6.9.0.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
It looks like the error is because of the employee field in the `Department` entity.  Can you try something like [this](https://github.com/sendilkumarn/jhipster-kotlin/commit/ef3b418247c46106269c0aee5e4cb89df7f96877#diff-a3b7cdbaeac75a44f127c46f735a5a10R159-R169).
