### ISSUE TITLE
Empty "Entities" menu

### ISSUE THREAD

**Issue by tonsV2** [jhipster/jhipster-kotlin#253]
## Overview of the issue

I'm facing the empty menu issue which is also described [here](https://github.com/jhipster/generator-jhipster/issues/5335) and [here](https://github.com/jhipster/generator-jhipster/issues/5192).

I've imported entities and can see them just fine using the H2 web console.

```
$ ls -l .jhipster/
total 36K
-rw-r--r--. 1 tons tons 1,2K Jul 26 01:38 Exercise.json
-rw-r--r--. 1 tons tons  685 Jul 26 01:38 Picture.json
...
-rw-r--r--. 1 tons tons  679 Jul 26 01:38 Video.json
```

I start my backend using `./gradlew` and I do `npm start` (in another terminal). I've also tried to do `./gradlew clean`, `npm install` and `npm run cleanup` before doing the above commands.

Any clue what I'm doing wrong?

## KHipster Version(s)

6.10.1

-   [/] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Did you generate the entities with `khipster entities` command ?

**Comment by sendilkumarn** [comment]
Closing this as invalid. But feel free to re-open if it is missing after running `khipster entity Exercise && khispter entity Picture && khipster entity Video`.
