### ISSUE TITLE
Reproducible builds with Gradle

### ISSUE THREAD

**Issue by isaul32** [jhipster/jhipster-kotlin#258]
## Overview of the issue
Ktlint formatting should be done before copying/diffing files because it cause many conflicts currently.

## Reproduce the error

1. Run khipster and use Gradle
2. Run khipster again
3. Get lot of conflicts

## KHipster Version(s)
KHipster v1.8.1
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
The upgrade sub-generator is not completed yet and also I think this might be due to base generator. Closing this for now. But please feel free to re-open or send a PR by adding the `upgrade` sub generator.
