### ISSUE TITLE
Microservices + oauth2 doesn't work

### ISSUE THREAD

**Issue by julillosamaral** [jhipster/jhipster-kotlin#269]
## Overview of the issue
After creating a brand new application with a Gateway and a microservices using both oauth2 the microservices always return 401 when doing a call to the API.
This behaviour doesn't happen in jhipster, did the same process with it and it works.
## Reproduce the error

1. Create a new Gateway using oauth2. For simplicity just use in memory and leave all the other values as default.
2. Create a new microservice using oauth2 and with all the defaults.
3. Create an entity in this microservice and import it in the Gateway (to have the frontend).
4. Start keycloack and registry and start the two services.
5. Go to the app, login.
6. When entering in `Entities` -> `New Entity` the microservice returns a 401. but we can access all the gateway endoints.

## KHipster Version(s)
6.10.5

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Closing this in favor of #255
