### ISSUE TITLE
Jhipster 7 support?

### ISSUE THREAD

**Issue by rburgst** [jhipster/jhipster-kotlin#273]
## Overview of the issue

it would be cool to support Jhipster 7

## Motivation for or Use Case

Stay up to date

## KHipster Version(s)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by davideme** [comment]
@sendilkumarn If you have any task we can help with to support v7, let me know. As I'm not sure the process you follow if you rebase from jhipster or importing the files.

**Comment by sendilkumarn** [comment]
I have done most of the work in nextv7 branch in this repo. The remaining work is to fix the failing tests. 

Please feel free to grab anyone pipeline if needed and fix them.

**Comment by sendilkumarn** [comment]
currently blocked by this error https://github.com/jhipster/generator-jhipster/issues/14492

**Comment by rburgst** [comment]
did you try adding `ajv` as a direct dependency?

**Comment by davideme** [comment]
I tested with jhipster 7.0.1 as based on the branch and seems working fine now.

**Comment by sendilkumarn** [comment]
Thanks @rburgst & @davideme it was due to npm 7 & npm 6 dependency tree issue.

The actual v7 migration is happening in this PR - #276
