### ISSUE TITLE
Running ktlint with Maven

### ISSUE THREAD

**Issue by emilpaw** [jhipster/jhipster-kotlin#275]
## Overview of the issue
In the pom.xml ktlint is set as one of the plugins but I can't figure out how to run it.
The ktlint-maven-plugin documentation suggests the khipster default setting for ktlint does "Formatting as part of the build" but building with `./mvnw` does not seem to format any code.

## Motivation for or Use Case
Consistent code is better code.

## Reproduce the error
1. Create project with khipster (select maven)
2. Mess up the code formatting
3. Run `./mvnw`

## KHipster Version(s)
6.10.5

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by emilpaw** [comment]
I figured it does actually work, but I looked for changed indentation and it seems ktlint does not auto-intend.

**Comment by sendilkumarn** [comment]
Thanks! you can find more about the usage [here](https://gantsign.com/ktlint-maven-plugin/usage.html).

> I figured it does actually work, but I looked for changed indentation and it seems it does not auto-indent. I think this is an issue with the plugin though, since running ktlint on the files does also intend them.

Interesting!  Can you create an issue at the maven-plugin repo? 

Closing this ticket for now. Please feel free to reopen if needed.
