### ISSUE TITLE
Error executing docker-compose on install

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-kotlin#281]
## Overview of the issue

Using the latest version, when I run `khipster jdl reactive-ms`, it has an error when generating Docker Compose files:

<img width="1330" alt="Screen Shot 2021-05-02 at 7 28 08 PM" src="https://user-images.githubusercontent.com/17892/116834757-c38ca180-ab7c-11eb-86f4-37fc8b90919b.png">

```
INFO! No custom sharedOptions found within blueprint: generator-jhipster-kotlin at /usr/local/lib/node_modules/generator-jhipster-kotlin
INFO! No custom commands found within blueprint: generator-jhipster-kotlin at /usr/local/lib/node_modules/generator-jhipster-kotlin
error: unknown option '--no-skip-ktlint-format'
INFO! Generator docker-compose child process exited with code 1
ERROR! Error executing docker-compose --no-force --no-dry-run --no-whitespace --no-bail --no-skip-regenerate --no-skip-yo-resolve --from-jdl --blueprints kotlin --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git --no-skip-ktlint-format --skip-prompts
Error: Error executing docker-compose --no-force --no-dry-run --no-whitespace --no-bail --no-skip-regenerate --no-skip-yo-resolve --from-jdl --blueprints kotlin --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git --no-skip-ktlint-format --skip-prompts
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/cli/import-jdl.js:183:16)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

## Motivation for or Use Case

I'd like to be able to write my reactive microservices with Kotlin!

## Reproduce the error

```
khipster jdl reactive-ms
```

## KHipster Version(s)

1.12.1

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Can you remove the `--no-skip-kotlin-flag` ? The flag is `--skip-kotlin-flag`.

**Comment by mraible** [comment]
I didn't add any options. All I did was run `khipster jdl reactive-ms`.

**Comment by sendilkumarn** [comment]
@mraible do you have any custom script for the docker-compose?  I just tried it and it works for me. 

I am not sure from where this is getting executed 

```
docker-compose --no-force --no-dry-run --no-whitespace --no-bail --no-skip-regenerate --no-skip-yo-resolve --from-jdl --blueprints kotlin --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git --no-skip-ktlint-format --skip-prompts
```

**Comment by mraible** [comment]
Not that I know of. Here's my versions of Node and npm:

```
$ node --version
v14.16.1
$ npm --version
7.11.2
```

I just tried uninstalling everything.

```
npm uninstall -g generator-jhipster generator-jhipster-kotlin
```

It seems to have worked:

```
$ jhipster
zsh: command not found: jhipster
$ khipster
zsh: command not found: khipster
```

Then I installed them both:

```
$ npm i -g generator-jhipster generator-jhipster-kotlin
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 1034 packages, and audited 1035 packages in 25s

72 packages are looking for funding
  run `npm fund` for details

1 critical severity vulnerability

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

NOTE: I included the output because there's a critical vulnerability, not sure what it is though.

Next, I tried to create reactive microservices with KHipster.

```
$ take apps
$ khipster jdl reactive-ms
```

It still happens for me. Maybe someone else can try it? @deepu105 @jdubois 

<img width="1442" alt="Screen Shot 2021-05-04 at 8 34 04 AM" src="https://user-images.githubusercontent.com/17892/117020318-91319000-acb3-11eb-891d-ce6786dba961.png">

**Comment by sendilkumarn** [comment]
This is weird. It looks like jdl assumes there will be a `no-<option>` 


Also if the application is generated, can you run `khipster docker-compose` seprately? Does it work?

**Comment by sendilkumarn** [comment]
@mraible can you uninstall jhipster alone and try?

**Comment by sendilkumarn** [comment]
Create https://github.com/jhipster/generator-jhipster/issues/14870 as a follow-up. For now, we can either remove the `--skip-ktlint-format` flag or generate the `docker-compose` files separately.

**Comment by mraible** [comment]
I uninstalled generator-jhipster, reinstalled generator-jhipster-kotlin and I can still reproduce the issue. The JDL question is probably a good one for @MathieuAA.

**Comment by mshima** [comment]
Drop default value https://github.com/jhipster/jhipster-kotlin/blob/e92416f9f5766d33cb42c4e09cedea9b18b32060/generators/app/index.js#L31

**Comment by mshima** [comment]
I think `--interactive` option may be used as workaround.

**Comment by sendilkumarn** [comment]
removing `default` does not completely fix the issue. With `default` removed the generator will error out if we supplied `--skip-ktlint-format` flag for `import-jdl`
