### ISSUE TITLE
Using Istio for local development

### ISSUE THREAD

**Issue by chess-equality** [jhipster/jhipster-kotlin#282]
## Overview of the issue

Hello,

I am following the blog post on using Istio with KHipster:

https://sendilkumarn.com/blog/khipster-microservices-k8s-istio/

Actually this is just a question, how do I test / develop first with my local without deploying to GCP?

What would be my local setup in this case?

Thanks for the help.
## Motivation for or Use Case
https://sendilkumarn.com/blog/khipster-microservices-k8s-istio/
## KHipster Version(s)
1.12.1
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
I think the steps are fairly similar, just do the following

- Docker Desktop
- Install / Enable Kubernetes
- Install Istio (following the blog, but in your local)

then just follow the blog.

**Comment by chess-equality** [comment]
But it will mean then that I need to deploy to Kubernetes every time I make a code change? I'm describing how the local development cycle would be.

**Comment by sendilkumarn** [comment]
@chess-equality Closing this issue since it is not related to the generator. Yeah if you're using Istio + k8s you would require the code changes to be deployed to the cluster.
