### ISSUE TITLE
Wrong mapping entity generation

### ISSUE THREAD

**Issue by julillosamaral** [jhipster/jhipster-kotlin#302]
## Overview of the issue
On the * to one relationships on jhipster a mapping was added to retrieve the data in the following way:
<img width="515" alt="Screen Shot 2021-10-12 at 10 41 34 AM" src="https://user-images.githubusercontent.com/979882/136967292-68ba13bc-1b69-4f13-aa83-61ca931b8a19.png">

Basically jhipster only loads the relationship field specified on the entity definition and the id.

On khipster the id as well as the relationship field are null as seen on the picture

<img width="558" alt="Screen Shot 2021-10-12 at 10 58 34 AM" src="https://user-images.githubusercontent.com/979882/136970303-7ad3c06d-d084-4c1b-ba78-e6b2e2c34322.png">

This behavior is inconsistent between tools and I think it could be wrong on khipster, even though I don't really like the jhipster approach. Also on khipster I don't have a way to fetch the relationship between the fields to the frontend.

## Motivation for or Use Case

Make both tools consistent and have a way to fetch relationships through the API

## Reproduce the error
I'm attaching two code samples, one for jhipster and other for khipster. But it's super easy to reproduce, you only have to add a to one relationship between two entities and fetch data from the one that exposes the relationship.

On the apis zip you can find two folders, one with a jhipster version and other with a khipster one. The .jhipster folder to generate the entities is also provided as well an updated fake data for the csv.

Please when testing update the fake data from liquibase to the one provided.

[apis.zip](https://github.com/jhipster/jhipster-kotlin/files/7330520/apis.zip)

## KHipster Version(s)
jhipster: 7.2.0
khipster: 1.12.1

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
@julillosamaral  KHipster is yet to support v7.2.0 of JHipster. That is the reason why you are seeing the difference here.

**Comment by sendilkumarn** [comment]
Closing this issue for now.
