### ISSUE TITLE
package.json needs updating so it doesn't reference eslint 3.7.2 which has been deprecated

### ISSUE THREAD

**Issue by kenyee** [jhipster/jhipster-kotlin#316]
## Overview of the issue
'@types/eslint-scope@https://artifactory.internal:443/api/npm/js-virtual/@types/eslint-scope/-/eslint-scope-3.7.2.tgz' is not in this registry

updating to latest node.js 17.3.0 also give this cryptic error when running khipster:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cli/utils' is not defined by "exports" in /Users/kenyee/.npm-global/lib/node_modules/generator-jhipster-kotlin/node_modules/generator-jhipster/package.json

## Motivation for or Use Case
Getting this error when doing an npm start.
Also tried doing npm update on the package.json but that didn't help either.

## Reproduce the error
npm start to start app

## Related issues
N.A.

## Link to PR (if any)
N.A.

## KHipster Version(s)
7.4.0
-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Closed via #333
