### ISSUE TITLE
Release 1.14.0

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-kotlin#319]
Related to https://github.com/jhipster/jhipster-kotlin/releases/tag/1.14.0

Adding a bounty for all the work done here @sendilkumarn

**Comment by sendilkumarn** [comment]
Thanks @pascalgrimaud 
Claimed :)

**Comment by pascalgrimaud** [comment]
@sendilkumarn : approved. Don't forget to put the link here, next time plz :pray: :)
