### ISSUE TITLE
import javax.persistence.SequenceGenerator is missing on User.kt

### ISSUE THREAD

**Issue by littlepine** [jhipster/jhipster-kotlin#321]
## Overview of the issue
A fresh generated project will fail on compile and throw following error:
```
error: incompatible types: NonExistentClass cannot be converted to Annotation
```

## KHipster Version(s)
1.14.0
-   [] Checking this box is mandatory (this is just to show you read everything)

In Case others also facing the error, apply the following to solve:
Add
```
import javax.persistence.SequenceGenerator
```
in Uesr.kt

**Comment by emilpaw** [comment]
Could you show your configuration? You can get it by running `jhipster info`.

**Comment by littlepine** [comment]
Thank you very much for your response.

Here is the jhipster info:

`
[32m[1mINFO![22m[39m Using JHipster version installed globally
[32m[1mINFO![22m[39m No custom sharedOptions found within blueprint: generator-jhipster-kotlin at /usr/local/lib/node_modules/generator-jhipster-kotlin
[32m[1mINFO![22m[39m No custom commands found within blueprint: generator-jhipster-kotlin at /usr/local/lib/node_modules/generator-jhipster-kotlin
[37mWelcome to the JHipster Information Sub-Generator[39m
[37m[39m
##### **JHipster Version(s)**

```
justorefw@0.0.1-SNAPSHOT /home/khipster/app
`-- (empty)

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "justorefw",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "js",
    "languages": ["en", "zh-tw"],
    "messageBroker": false,
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "testFrameworks": [],
    "websocket": false,
    "enableGradleEnterprise": false,
    "gradleEnterpriseHost": "",
    "applicationType": "monolith",
    "packageName": "hk.com.justmove.justorefw",
    "packageFolder": "hk/com/justmove/justorefw",
    "nativeLanguage": "en",
    "jhipsterVersion": "7.5.0",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "applicationIndex": 0,
    "entities": [
      "Contact",
      "BasicInfo",
      "Perference",
      "Customer",
      "Shipment",
      "Company",
      "PlatformUser",
      "Product",
      "ProductMetaData",
      "ProductVariant",
      "ProductTag",
      "ProductCategory",
      "Photo",
      "InventoryItem"
    ],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.14.0"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.14.0"
      }
    ],
    "pages": [],
    "creationTimestamp": 1641886164387,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "lastLiquibaseTimestamp": 1641887004000
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * The Contact entity.\n@author Pine Ng
 */
entity Contact {
  /**
   * Name
   */
  name String
  /**
   * Mobile Phone No
   */
  mobile String
  /**
   * Email
   */
  email String
}
/**
 * The BasicInfo entity.\n@author A true hipster
 */
entity BasicInfo {
  gender Gender
  birthday LocalDate
}
/**
 * The User Perference entity.\n@author A true hipster
 */
entity Perference {
  /**
   * The UI language Preference
   */
  language String
  currency String
  isReceivePromotionEmail Boolean
}
/**
 * Customer
 */
entity Customer {
  /**
   * Each Customer has an unique UUID (JCID / Justore Customer ID)\nCustomer can input a referral JCID when they register\nCustomer can send an referral link to any person, the referral link will direct user to customer registration page with referral JCID prefilled\nAfter referred customer successfully registered, (Customer) -[REFER] -> (Customer) will be saved to customer service DB.
   */
  jcid UUID
  userInfoId Long
}
/**
 * Shipment Information
 */
entity Shipment {
  isDefaultShipment Boolean
  deliveryAddress String
}
/**
 * The Company entity.\n@author A true hipster
 */
entity Company {
  /**
   * A global identifier for business party in the network
   */
  jsid String
  /**
   * The registration no from government
   */
  businessRegistrationNo String
  /**
   * This name will be used on report and contract
   */
  businessName String
  /**
   * This name used for UI display and greeting screen
   */
  displayName String
}
/**
 * The PlatformUser entity.\n@author A true hipster
 */
entity PlatformUser {
  plaformRole PlatformRole
}
/**
 * The Product entity. Keep tract the product publishing status\n@author A true hipster
 */
entity Product {
  /**
   * A unique id to identify the company current product belongs to
   */
  jsid String
  /**
   * A unique id to identify the product in the whole system
   */
  jpid UUID
  brandName String
  /**
   * A Json Map to store the variant information, here is an example format:\n```\n{\n"Size":["M","L","XXL"],\n"Color":["Sunshine Yellow", "Dark"]\n}\n```
   */
  variantSpec String
  published Boolean
  highlight Boolean
  allowOversell Boolean
  valid Boolean
  commentCount Integer
  rating Float
  createdDate LocalDate
}
/**
 * The ProductMetaData entity.\n@author A true hipster
 */
entity ProductMetaData {
  /**
   * A unique id to identify the company current product belongs to
   */
  jsid String
  /**
   * A unique id to identify the product in the whole system
   */
  jpid UUID
  isDefault Boolean
  langCode String
  langName String
  name String
  description String
  feature String
  valid Boolean
  createdDate LocalDate
  lastModifiedDate LocalDate
}
/**
 * The ProductVariant entity.\n@author A true hipster
 */
entity ProductVariant {
  /**
   * The specification of current variant, in comma separated format:\n"XL, red"
   */
  spec String
  sku String
  photoId String
  displayPrice Double
  actualPrice Double
  supplierPrice Double
  discounted Boolean
  allowOversell Boolean
}
/**
 * The Tag entity.\n@author A true hipster
 */
entity ProductTag {
  /**
   * The content of current Tag
   */
  content String
  /**
   * The frequency of current Tag
   */
  conut Integer
}
/**
 * The ProductCategory entity.\n@author A true hipster
 */
entity ProductCategory {
  /**
   * A unique id to identify the company current product belongs to
   */
  jsid String
  /**
   * the count of products under this category
   */
  productCount Integer
  /**
   * the url to this category
   */
  displayURL String
  published Boolean
}
/**
 * The Photo entity.\n@author A true hipster
 */
entity Photo {
  /**
   * the id in string to identify the picture
   */
  photoId String
  /**
   * where the photo hosted
   */
  provider String
}
/**
 * The InventoryItem entity. Keep tract the stock data\n@author A true hipster
 */
entity InventoryItem {
  /**
   * fieldName
   */
  fieldName String
}
enum Gender {
  MALE,
  FEMALE,
  UNKNOWN
}
/**
 * TODO: Identity different role function
 */
enum PlatformRole {
  Supplier,
  Seller,
  SellerAdmin,
  Customer,
  CustomerGroup,
  User
}

relationship OneToOne {
  BasicInfo{avatar} to Photo
  Customer{contact} to Contact
  Customer{info} to BasicInfo
  Customer{preference} to Perference
  Customer{user} to PlatformUser
  Shipment{contact} to Contact
  Company{user} to PlatformUser
  Company{products} to Product
  Company{productCategories} to ProductCategory
  ProductVariant{inventory} to InventoryItem
}
relationship OneToMany {
  Company{clients} to Customer{company}
  Customer{referees} to Customer{customer}
  Customer{deliveryDestinations} to Shipment{customer}
  ProductCategory{products} to Product{productCategory}
  Product{metaData} to ProductMetaData{product}
  ProductCategory{metaData} to ProductMetaData{productCategory}
  Product{variants} to ProductVariant{product}
  Product{tags} to ProductTag{product}
  ProductCategory{keywords} to ProductTag{productCategory}
  Product{photos} to Photo{product}
  ProductCategory{photos} to Photo{productCategory}
}


</pre>
</details>


##### **Environment and Tools**

git version 2.25.1

node: v14.15.0

npm: 8.5.3


No change to package.json was detected. No package manager install will be executed.
[32m[1mCongratulations, JHipster execution is complete![22m[39m
[36m[1mSponsored with ❤️  by @oktadev.[22m[39m


`
