### ISSUE TITLE
[Feature Discussion] Khipster with pure Kotlin

### ISSUE THREAD

**Issue by assimbly** [jhipster/jhipster-kotlin#323]
Not really an issue, more of a question/idea:

Currently, Spring Boot and some popular front-end framework (React/Angular/Vue) are used to generate a Kotlin webapplication. 

Are there any plans to make a generator for a pure Kotlin generated application? (where developers can code 100% in Kotlin)

For example:

1) Backend: Ktor (https://ktor.io/)
2) Frontend: Kvsion (https://github.com/rjaros/kvision)
3) Build: Gradle for Kotlin DLS (https://docs.gradle.org/current/userguide/kotlin_dsl.html)

**Comment by littlepine** [comment]
I think unless you have a very legitimate reason of doing this, the requirement should not treat as the scrope of this project.
As this project is literally a kotlin version of Jhipster, which itself already have a messive amount of work and resource to maintain.

Also you should also study how Spring vs Ktor, Kvsion vs Angular, what is the pros and cons of those technology?

making request is easy, but this require huge amount of work.

**Comment by skin27** [comment]
@littlepine Hi I know, I manage a Jhipster based open source project myself (https://api.github.com/repos/assimbly/gateway). 

This was not really a request, but more just an idea/discussing thread. It's still kind of a dream to code a web/mobile application 100% in one language with an excellent language as Kotlin. Now with new projects and also with the push of Jetbrains of Kotlin with WASM as target, this seems to be possible. The tradeoffs are interesting to investigate (currently I am only thinking of the benifits :) ).

If you have thoughts about, would be nice to share. You can of course close the issue as this is not part of the Khipster project.

**Comment by sendilkumarn** [comment]
@assimbly  this is what I really wanted at the beginning, but as @littlepine pointed out maintaining the changes happening on JHipster itself is a huge work and we need more resources and community help here. 

If we get enough traction and community support in these areas, I am more than happy to generate a project that is entirely Kotlin and supports wide variety of Kotlin based frameworks.
