### ISSUE TITLE
Errors with freshly generated project

### ISSUE THREAD

**Issue by Digital-Nomad** [jhipster/jhipster-kotlin#328]
I am running into these errors with a freshly generated project. 
[output console](https://imgur.com/D2ZndOX)

I am running 
typescript version: 4.6.2
npm version: 8.3

Any ideas?

**Comment by sendilkumarn** [comment]
This looks like frontend error(s) and also in the entities. Can you ensure JHipster version is KHipster supported version?

**Comment by emilpaw** [comment]
@Digital-Nomad Could you try this? https://github.com/jhipster/jhipster-kotlin/issues/330#issuecomment-1066076698
