### ISSUE TITLE
[Fix] React frontend react-router-dom types

### ISSUE THREAD

**Issue by emilpaw** [jhipster/jhipster-kotlin#330]
## Overview of the issue
A freshly generated React frontend throws errors: 
```
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: RouterProps | Readonly<RouterProps>): Router', gave the following error.
    Type 'MemoryHistory' is missing the following properties from type 'History<unknown>': length, goBack, goForward
  Overload 2 of 2, '(props: RouterProps, context: any): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
    38 |     const history = createMemoryHistory();
    39 |     const { container } = wrapper(
  > 40 |       <Router history={history}>
       |               ^^^^^^^
    41 |         <PrivateRouteComponent component={TestComp} path="/" />
    42 |       </Router>,
    43 |       {

ERROR in src/main/webapp/app/shared/auth/private-route.spec.tsx:59:15
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: RouterProps | Readonly<RouterProps>): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
  Overload 2 of 2, '(props: RouterProps, context: any): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
    57 |     const history = createMemoryHistory();
    58 |     const { container } = wrapper(
  > 59 |       <Router history={history}>
       |               ^^^^^^^
    60 |         <PrivateRouteComponent component={TestComp} path="/" />
    61 |       </Router>,
    62 |       {

ERROR in src/main/webapp/app/shared/auth/private-route.spec.tsx:76:15
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: RouterProps | Readonly<RouterProps>): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
  Overload 2 of 2, '(props: RouterProps, context: any): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
    74 |     const history = createMemoryHistory();
    75 |     const { container } = wrapper(
  > 76 |       <Router history={history}>
       |               ^^^^^^^
    77 |         <PrivateRouteComponent exact component={TestComp} path="/" />
    78 |       </Router>,
    79 |       {

ERROR in src/main/webapp/app/shared/error/error-boundary-route.spec.tsx:27:15
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: RouterProps | Readonly<RouterProps>): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
  Overload 2 of 2, '(props: RouterProps, context: any): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
    25 |     const history = createMemoryHistory();
    26 |     const { container } = render(
  > 27 |       <Router history={history}>
       |               ^^^^^^^
    28 |         <ErrorBoundaryRoute component={ErrorComp} path="/" />
    29 |       </Router>
    30 |     );

ERROR in src/main/webapp/app/shared/layout/header/header.spec.tsx:41:19
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: RouterProps | Readonly<RouterProps>): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
  Overload 2 of 2, '(props: RouterProps, context: any): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
    39 |       const { container } = render(
    40 |         <Provider store={store}>
  > 41 |           <Router history={history}>
       |                   ^^^^^^^
    42 |             <Header {...props} />
    43 |           </Router>
    44 |         </Provider>

ERROR in src/main/webapp/app/shared/layout/menus/account.spec.tsx:15:17
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: RouterProps | Readonly<RouterProps>): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
  Overload 2 of 2, '(props: RouterProps, context: any): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
    13 |       const history = createMemoryHistory();
    14 |       const { container } = render(
  > 15 |         <Router history={history}>
       |                 ^^^^^^^
    16 |           <AccountMenu isAuthenticated />
    17 |         </Router>
    18 |       );

ERROR in src/main/webapp/app/shared/layout/menus/account.spec.tsx:27:17
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: RouterProps | Readonly<RouterProps>): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
  Overload 2 of 2, '(props: RouterProps, context: any): Router', gave the following error.
    Type 'MemoryHistory' is not assignable to type 'History<unknown>'.
    25 |       const history = createMemoryHistory();
    26 |       const { container } = (mountedWrapper = render(
  > 27 |         <Router history={history}>
       |                 ^^^^^^^
    28 |           <AccountMenu />
    29 |         </Router>
    30 |       ));


``` 

## Motivation for or Use Case
React frontend should work.

## Related issues
The issue apparently was fixed in version 7.7 of JHipster: https://github.com/jhipster/generator-jhipster/issues/17614
Bumping the version of @types/react-router-dom resolved the issue: https://github.com/jhipster/generator-jhipster/pull/17607

## KHipster Version(s)
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-kotlin at /home/user/.nvm/versions/node/v16.14.0/lib/node_modules/generator-jhipster-kotlin
INFO! No custom commands found within blueprint: generator-jhipster-kotlin at /home/user/.nvm/versions/node/v16.14.0/lib/node_modules/generator-jhipster-kotlin
(node:74353) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./cli/" in the "exports" field module resolution of the package at /home/user/jhipster-contributions/jhipster-kotlin/node_modules/generator-jhipster/package.json.
Update this package.json to use a subpath pattern like "./cli/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /home/user/jhipster-contributions/khipster-sample-react-stopped-working
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "skipJhipsterDependencies": true,
    "blueprints": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.14.0"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.14.0"
      }
    ],
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.5.0",
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1647166593731,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)

git version 2.35.1

node: v16.14.0

npm: 8.3.1

Docker version 20.10.12, build e91ed5707e

Docker Compose version 2.2.3

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by emilpaw** [comment]
The workaround is to change `"@types/react-router-dom": "5.3.2",` to `"@types/react-router-dom": "5.3.3",`. 

@sendilkumarn Is there something we can do, besides upgrading KHipster to JHipster 7.7?

**Comment by mishkaechoes** [comment]
Oh thank you so much for this. I've been banging my head on this for awhile

**Comment by hubertgrzeskowiak** [comment]
Worked like a charm.
I first bumped the version of `react-router-dom` as well. That did not go well. Updating just the type definitions works, though.

**Comment by sendilkumarn** [comment]
Yeah we cannot do much here. upgrading the `react-router-dom` does the trick. I will release a new version asap, that will fix this. Thanks :) 


Closing this for now, please feel free to reopen if needed, thanks
