### ISSUE TITLE
[Bug/Fix] jhipster dependencies are still used in get methods while passing the `--skip-jhipster-dependencies`

### ISSUE THREAD

**Issue by SaltOfTheFlame** [jhipster/jhipster-kotlin#340]
## Overview of the issue
jhipster dependencies are still used in get methods while passing the `--skip-jhipster-dependencies`
## Reproduce the error

create any entity
mark it as readOnly
configurate application to use the reactive approach
generate with argument `--skip-jhipster-dependencies`
check out the Resource of this entity

## KHipster Version(s)
v1.14.0, v1.15.0

**Comment by sendilkumarn** [comment]
With the latest version, it looks like passing this argument, works as expected. 

Please feel free to reopen if the issue persists. Can you also add your JDL / .yo-rc.json file if you have to reopen.
