### ISSUE TITLE
[ERROR] Note: Hibernate JPA 2 Static-Metamodel Generator 5.6.7.Final

### ISSUE THREAD

**Issue by bobbungbia** [jhipster/jhipster-kotlin#341]
## Overview of the issue

When I running first time application with `./mvnw` . I'm facing with two problems :

- [ERROR] Note: Hibernate JPA 2 Static-Metamodel Generator 5.6.7.Final
- [ERROR] Failed to execute goal com.github.gantsign.maven:ktlint-maven-plugin:1.13.0:format (format) on project food: Execution format of goal com.github.gantsign.maven:ktlint-maven-plugin:1.13.0:format failed: An API incompatibility was encountered while executing com.github.gantsign.maven:ktlint-maven-plugin:1.13.0:format: java.lang.ExceptionInInitializerError: null

**Comment by sendilkumarn** [comment]
Can you please provide more details and reopen the issue?

**Comment by Triippz** [comment]
If anyone encounters this issue in the future, take a peek at this [issue](https://github.com/gantsign/ktlint-maven-plugin/issues/392#issuecomment-1114657552) for the klint maven plugin.
