### ISSUE TITLE
Update to JHipster 7.9.x dependency with Spring 2.7.0

### ISSUE THREAD

**Issue by codeindustriesnl** [jhipster/jhipster-kotlin#345]
## Overview of the issue
The 1.15.0 KHipster generator uses JHipster 7.8.1. JHipster generator has updated to 7.9.3 which has updated dependencies, e.g. Spring 2.7.0. 

## Motivation for or Use Case
Spring 2.7.0 is one of the updates in JHipster generator 7.9.x which has some relevant bug fixes.

## KHipster Version(s)
1.15.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@kingofDaniel Please stop spamming this repo by adding comments.

**Comment by sendilkumarn** [comment]
@codeindustriesnl started the migration in https://github.com/jhipster/jhipster-kotlin/tree/upgrade/7.9.3
