### ISSUE TITLE
Failed to compile on fresh KHipster project generation 

### ISSUE THREAD

**Issue by groblochon** [jhipster/jhipster-kotlin#39]
With JHipster 5.1.0 and lastest jhipster-kotlin blueprint, on a fresh monili I have 2 compilation error : 

- AuditResource#get -> id is a String instead of Long
- UserService#getUserWithAuthorities -> id is a String instead of Long
[kotlinCompileBug.txt](https://github.com/jhipster/jhipster-kotlin/files/2250120/kotlinCompileBug.txt)

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
This is mainly because of the mainstream changes, let me check that.

**Comment by sendilkumarn** [comment]
Fixed via e42adca39e7f1ed8c544159bb5d0f2b81635d9bd and 3e433b04ec54c5044aa60c5c99e1e85751803282

**Comment by sendilkumarn** [comment]
Release `0.5.0` version and it should work
