### ISSUE TITLE
Kotlin for UI modules

### ISSUE THREAD

**Issue by tharakadesilva** [jhipster/jhipster-kotlin#4]
Was wondering if it'd be possible to add Kotlin for UI modules generated for Angular and Kotlin.

**Comment by sendilkumarn** [comment]
It is possible to do this. But again that will be a huge work. Would love to have some contributors for this.

**Comment by tharakadesilva** [comment]
I could start working on it but I am probably going to need some help ;)

**Comment by sendilkumarn** [comment]
let us start with something simple there then, we will just generate the `glue` code that enables users to write kotlin based frontend files. Then we can migrate the entities to use this Kotlin generator and so on.

**Comment by deepu105** [comment]
Guys, I would suggest focussing on backend first as that is where Kotlin shines. For front-end I wouldn't recommend as you would want to use something like Kotlin-React to get descent SPA and doing frontend with Kotlin is ugly as hell from what I have seen. Just compare normal react code with same in Kotlin you will see what I'm talking about

**Comment by sendilkumarn** [comment]
@deepu105 exactly it is weird. That is the reason why I want to start with a gluecode. But this is not a priority.

**Comment by sendilkumarn** [comment]
Closing this for now
