### ISSUE TITLE
Failed to create entity using KHipster

### ISSUE THREAD

**Issue by groblochon** [jhipster/jhipster-kotlin#40]
Using JHipster v5.1.0 and latest jhipster-kotlin, on create entity with jdl or not, JHipster ask me to define a database.
[kotlinEntityBug.txt](https://github.com/jhipster/jhipster-kotlin/files/2250130/kotlinEntityBug.txt)

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Entity generation PR is still not merged. So, it is not possible to generate entities at the moment.

Refer #37

**Comment by JavierFuentes** [comment]
@sendilkumarn,
what is the status of this...?

I've just executed then command `$ jhipster --blueprint kotlin entity Todo` without errors but all new Classes are .java files

My version is:
```ts
$ jhipster --version
5.8.2
```

**Comment by sendilkumarn** [comment]
@JavierFuentes This should work even without the blueprint option. 

`jhipster entity Todo` will suffice. (provided the project is created with blueprint option enabled)

**Comment by JavierFuentes** [comment]
Sorry @sendilkumarn,
but I've reverted all unversioned files in my VCS and repeat the entity creation without `--blueprint` modifier but the results are exactly the same... all server files are .java files

My version of Yeoman is this
```ts
$ yo --version
2.0.5
```

And my `.yo-rc.json` content is this:
```json
{
    "generator-jhipster-kotlin": {
        "promptValues": {
            "packageName": "com.mycompany.myapp"
        },
        "jhipsterVersion": "5.7.2",
        "applicationType": "monolith",
        "baseName": "jhkPrueba",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": "spring-websocket",
        "databaseType": "sql",
        "devDatabaseType": "mysql",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": true,
        "jwtSecretKey": "<the-secret>"
    },
    "generator-jhipster": {
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "jhkPrueba",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": ["gatling", "protractor"],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [
            {
                "name": "generator-jhipster-kotlin",
                "version": "0.7.0"
            }
        ],
        "enableTranslation": false,
        "blueprint": "generator-jhipster-kotlin",
        "blueprintVersion": "0.7.0"
    }
}
```

I only apreciate that `jhipsterVersion` doesn't match between `generator-jhipster-kotlin` and `generator-jhipster` entries but I don't know if this is the problem...

If I execute this inside my project's folder, this is the result:

```
$ jhipster --version
INFO! Using JHipster version installed locally in current project's node_modules
5.8.2
```

If I execute this outside my project's folder, the version is the same:

```
$ jhipster --version
INFO! Using JHipster version installed globally
5.8.2
```

I hope you can reproduce the scenario...

**Comment by JavierFuentes** [comment]
Hi @sendilkumarn,
you have been able to reproduce the escenario?

Am I the only one that jhipster-kotlin generator blueprint generates entities in Java instead of Kotlin?

**Comment by pvliss** [comment]
Hello @JavierFuentes. You are currently using Kotlin blueprint 0.7.0 which is the latest release **but** the entity generator PR(#74) was merged after that(see [commit history](https://github.com/jhipster/jhipster-kotlin/commits/master)). Currently the only way you can use the entity generator is by using the master branch. Sorry

We are working now to finish updating to JHipster 6.x(SB 2.1)(also still in development) and simultaneously reach full feature parity with the Java generator(see #98 )

@sendilkumarn Would it make sense to release a new version from current master so that the entity generator could be used?
