### ISSUE TITLE
Fix the failing gradle build in CLI 

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#41]
This is super annoying, we can build the project in IntelliJ without any issues but in the command line it is having a problem, `compileJava` cannot find the `Kotlin compiled classes`

After hours and hours of debugging, the root cause is because `Java` cannot find the detect types of `Kotlin compiled classes`

While this code fails  in CLI

```kt
fun getAccount(): UserDTO {
        return userService.getUserWithAuthorities()
            .map { UserDTO(it) }
            .orElseThrow { InternalServerErrorException("User could not be found") }
    }
```

but this passes in CLI

```kt
fun getAccount(): UserDTO {
        val user = userService.getUserWithAuthorities()?: throw InternalServerErrorException("User could not be found")
        return UserDTO(user.get())
    }
```

**Comment by deepu105** [comment]
Did you configure the classpaths for Kotlin. Newer gradle versions use
seperate folder per source

**Comment by sendilkumarn** [comment]
Apparently, the reason is due to the `package-info.java` file. Removing that works perfectly. Strange reason took a loooot of time to understand this.

**Comment by sendilkumarn** [comment]
Can we remove the `package-info.java` files completely?

**Comment by jonvallet** [comment]
Would be interesting to know why gradle fails to compile if package-info.java is present.
