### ISSUE TITLE
Bugfix: Pass command line arguments to application

### ISSUE THREAD

**Issue by rainerh** [jhipster/jhipster-kotlin#48]
Overview of the issue
The generated Kotlin application does not pass command line arguments on to the application.

Motivation for or Use Case
Fix the bug

Reproduce the error
Start application with prod profile, the dev profile ist still being used.

Related issues
none

Link to PR (if any)
https://github.com/jhipster/jhipster-kotlin/pull/47

JHipster Version(s)
5.4.2 and earlier

[X] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Closing this as #47 is merged.
