### ISSUE TITLE
Update Travis

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-kotlin#53]
The Travis build needs to be updated, using the new folder `test-integration` as the `travis` folder is deprecated and will be deleted in future.

@sendilkumarn : can you assign me to this ticket plz ? So I won't forget to do it

**Comment by sendilkumarn** [comment]
Awesome thanks 👍

**Comment by sendilkumarn** [comment]
Can you also raise a PR against move-5.6 branch?

**Comment by pascalgrimaud** [comment]
yes ok

**Comment by pascalgrimaud** [comment]
Closing this, as the PR has been merged
