### ISSUE TITLE
Migrate entity generator into Kotlin

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/jhipster-kotlin#6]
Migrate the existing entity generator to Kotlin

This will include

- [ ] migrating the resource files
- [ ] migrating the repositories
- [ ] migrating the domain
- [ ] migrating the service layer

**Comment by hberndt** [comment]
I start working on this issue.

**Comment by hberndt** [comment]
I need some help on overwriting the generator scripts. I do not understand how to overwrite index.js and files.js. I always get a warning: No blueprint found for entity. I only want to change entity-server. Any ideas? Is there any documentation on implemeting a blueprint?

**Comment by thodorisbais** [comment]
Hi @hberndt , indeed, there is currently something missing in the configuration so that we can make it work. As soon as we fix this, we will let you know.

**Comment by hberndt** [comment]
@sendilkumarn I made a new branch from the master. But within the server templates index and files are not the same as in the jhipster generator. That was the reason for me to change them for the entity-generator. I am familiar with JAVA and Kotlin but I am not familiar with the YEOMAN generator architecture. May I get some help for the entity generator starting point?

**Comment by sendilkumarn** [comment]
@hberndt there is a problem with the current master. 

@deepu105 Do you have any idea when can you work on this, after vacation?

**Comment by sendilkumarn** [comment]
It is ready :)

**Comment by hberndt** [comment]
:-) would be great but I get 

`events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/hberndt/Projects/jhipster-kotlin/node_modules/generator-jhipster/generators/server/templates/gitattributes.ejs`

**Comment by deepu105** [comment]
May be you are on Yarn 1.7, if so please downgrade to 1.6

**Comment by hberndt** [comment]
Mmmh. I don't know why yarn should be responsible (it is a dependency manager?)
Nevertheless I downgraded to 1.6 but the error still remains. All calls to the generator template function work. Only the copy function throw this error. If the source file does not exists in the blueprint there will no fallback to the jhipster original.

**Comment by sendilkumarn** [comment]
The particular file is from the base generator. Can you please remove node_modules and do yarn install again in your jhipster-kotlin folder? 

Also if you still have the error, 
Please post the entire stack. 
Where is your generator-jhipster location? 
Did you link jhipster insider jhipster-kotlin?

**Comment by deepu105** [comment]
@hberndt coz I ran into similar issues due to some issue in Yarn link, a bug from 1.7 onwards. So if you are working on blueprint stick to Yarn 1.6 or use 1.9 snapshots

**Comment by hberndt** [comment]
Well, first many thanks. That info works. 
I developed the entity generator but JHipster does not recognize the blueprint. I pushed my code into a branch within my forck (https://github.com/hberndt/jhipster-kotlin/tree/entity-generator).Would be great if anyone would review my generator code. JHipster 5.0.1 always prompts for a new application even if I use "entity" param.
Thanks for any advice.

**Comment by sendilkumarn** [comment]
The initial version is done. Needs a lot of fixes
