### ISSUE TITLE
installation not detected in JHipster

### ISSUE THREAD

**Issue by garfieldnate** [jhipster/jhipster-kotlin#64]
When I try to generate a project with JHipster using this plugin, JHipster complains that it is not installed. 

Following the instructions in the readme:

    $ npm install -g generator-jhipster-kotlin
    + generator-jhipster-kotlin@0.6.1
    updated 1 package in 12.901s
    $ jhipster --blueprint kotlin
    INFO! Using JHipster version installed globally
    INFO! Running default command
    INFO! Executing jhipster:app
    INFO! Options: blueprint: kotlin, from-cli: true

    ...

    Welcome to JHipster v5.7.0

    ...

    events.js:167
          throw er; // Unhandled 'error' event
          ^

    Error: ERROR! The generator-jhipster-kotlin blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-kotlin.
        at Environment.error (/Users/nglenn/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
        at module.exports.error (/Users/nglenn/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:2444:18)
        at shelljs.exec (/Users/nglenn/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base-private.js:794:22)
        at /Users/nglenn/.config/yarn/global/node_modules/shelljs/src/exec.js:124:9
        at ChildProcess.exithandler (child_process.js:301:5)
        at ChildProcess.emit (events.js:182:13)
        at maybeClose (internal/child_process.js:978:16)
        at Socket.stream.socket.on (internal/child_process.js:395:11)
        at Socket.emit (events.js:182:13)
        at Pipe._handle.close (net.js:616:12)
    Emitted 'error' event at:
        at Environment.error (/Users/nglenn/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:159:15)
        at module.exports.error (/Users/nglenn/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:2444:18)
        [... lines matching original stack trace ...]
        at Pipe._handle.close (net.js:616:12)

JHipster version v5.7.0, Node version v11.3.0

[X] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
@garfieldnate can you try linking the Kotlin-hipster on the folder?  or else try it without installing the main generator.

**Comment by garfieldnate** [comment]
I'm not exactly sure from your comment what you are asking me to try, but I did the following:

`npm uninstall -g generator-jhipster-kotlin`, then `jhipster --blueprint kotlin` -> same error output.

`git clone https://github.com/jhipster/jhipster-kotlin.git`, `cd jhipster-kotlin`, `npm link`, `jhipster --blueprint kotlin` -> same error output.

**Comment by sendilkumarn** [comment]
For the second one, inside the folder where you are generating the application run `npm link "generator-jhipster-kotlin"`

**Comment by garfieldnate** [comment]
I tried it but the error is still the same.

**Comment by kbednarz** [comment]
I've got the same error and after short debugging I noticed `generator-jhipster` executes `yo --generators` to get available blueprints. In my case I've just missed Yeoman. Try to install it with `npm install -g yo`.

**Comment by sendilkumarn** [comment]
@kbednarz That is indeed an interesting finding. Thanks. @garfieldnate  can you confirm it?

`yo` is the basic requirement for JHipster to run.

**Comment by garfieldnate** [comment]
Ah, that fixed the error.

I'm still puzzled, though, because no Kotlin files were generated. Only Java.

    INFO! Congratulations, JHipster execution is complete!

    $ find . -name "*.kt"
    
    $

**Comment by pvliss** [comment]
@garfieldnate Did you use maven or gradle as the build tool? It seems there is a bug for gradle generation. Was about to report it and investigate it.

**Comment by garfieldnate** [comment]
@pvliss I'm using gradle. Your advice made everything work! So there are two issues here:

1. It doesn't work out-of-the-box from NPM like it should. You have to `clone` `generator-jhipster` and `jhipster-kotlin` and build and link them, whereas the readme specifies (quite sensibly) that one should only do `npm install -g generator-jhipster-kotlin`. 
2. Yeoman needs to be a dependency, or otherwise some special exception should be thrown if it is not installed.

**Comment by fguo** [comment]
I can only generate several config files with Kotlin. Other files are generated in java. Is this normal?

**Comment by sendilkumarn** [comment]
@fguo yeah, currently the generator works like this.

**Comment by JavierFuentes** [comment]
Same problem with jhipster v5.8.2 and jhipster-kotlin...

> 2. Yeoman needs to be a dependency, or otherwise some special exception should be thrown if it is not installed.

I just reviewed [jhipster install page] (https://www.jhipster.tech/installation/) and efectivelly says this in step 4:

> If you want to use the JHipster Marketplace, install Yeoman: npm install -g yo

**Comment by pvliss** [comment]
@JavierFuentes Thanks for reporting. So I assume you got it working after installing yeoman, right? And yes I think yeoman is a requirement for getting it to work properly.

@sendilkumarn Maybe we need to revisit the docs. I will try to find some time over the weekend to update them.

**Comment by JavierFuentes** [comment]
@pvliss, 
yes the generator is working now.

**Comment by pvliss** [comment]
Thanks @JavierFuentes . We will update the docs accordingly

**Comment by JavierFuentes** [comment]
Hi @pvliss,
I said you that generator was working after install yeoman, but after that I reported in [this comment](https://github.com/jhipster/jhipster-kotlin/issues/40#issuecomment-471226507) that Entities was generating in Java code instead of Kotlin code...

Do you know if there is any kind of bug that produces this behavior?

**Comment by sendilkumarn** [comment]
Not closed yet.

**Comment by mrts** [comment]
See also https://github.com/jhipster/jhipster-vuejs/issues/369 - in certain circumstances you have to install both the blueprint and *yo* **locally** with 

```
npm i generator-jhipster-kotlin yo
```

(note the omission of `-g`) to make it work.
