### ISSUE TITLE
Update to Kotlin 1.3.11

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#69]
Update to the latest Kotlin stable, namely 1.3.11

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
@sendilkumarn I will also check the gradle build as well but before submitting a PR I think it would be best to wait  for #67 to be merged to avoid re-basing ,etc.

**Comment by sendilkumarn** [comment]
This will be an interesting fix. I would say check whether a vanilla Spring Boot 2.0.x supports this version of Kotlin before trying it in here. 

An easy way to test it.
