### ISSUE TITLE
Update to JHipster 5.7.2

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#70]
Update to JHipster 5.7.2

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
For UserMapper.kt.ejs (I have removed many kt files because it is hard to maintain them.) I think we should stop creating kt for base generator rather provide a platform for users to create the new files in Kotlin. I think that will be a good first step.
