### ISSUE TITLE
Feature parity with parent Java project

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#85]
### Overview of the issue

This is a list of generators and their sub-packages provided by the parent JHipster project in Java and need to be migrated to Kotlin:

**1st level:** Generators:
**2nd level:** Packages

~- [ ] aws-containers~ Removing this based on our discussion.
- [x] entity-server
- [x] server
  - [x] aop
  - [x] client (93)
  - [x] config (#86)
  - [x] domain (#91)
  - [x] gateway (#91)
  - [x] repository (#91)
  - [x] security (#91)
  - [x] service (#91)
  - [x] web (#91)
  - [x] cucumber (tests only) (#91)
- [x] spring-controller 
- [x] spring-service

**NOTES:**
1. Tests are not mentioned in the list but should be done alongside the main code 
2. The order is alphabetical

### Motivation for or Use Case
Achieve feature parity with parent JHipster Java project

### JHipster Version(s)
6.x

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
So I have started the porting and decided to first start with the `domain` package as the entity generator is now done and seemed logical to have all domain objects in Kotlin. I have completed the port but the problem is that several tests fail with `NullPointerException`s as when Java classes use the Kotlin constructors the default arguments are ignored. This is especially true for the `User` class as it is being used in many places. Hence, this will have to wait for now. 

I will  instead continue with the `configuration` and other packages and work towards the domain packages to avoid such problems.

**Comment by pvliss** [comment]
@sendilkumarn Just a status update. I have also finished with the `gateway` and `repository` packages as well but will wait for the merge of #86 first as it changed `server/files.js` heavily and I would like to avoid conflicts/difficult merges for the other PRs.

**Comment by amatosg** [comment]
@pvliss If it's ok with you, I would like to work on the service layer as of #89

**Comment by pvliss** [comment]
Hello @amatosg. You are more than welcome to help and help is really needed. I have actually already converted the service package. See the commits at #88. I am now pushing commits over there as they also target JHipster 6.x. Also I am just finishing the cucumber tests.

I will update what has already been done in the title. Then just pick what you are comfortable with and let us know.

**Comment by pvliss** [comment]
I have also done domain but have not pushed the commit yet.

**Comment by amatosg** [comment]
so, what's missing? I see _web_ but I'm not sure what layer is that.

**Comment by pvliss** [comment]
For anyone interested to help out I will continue with the migration of the repository package. Just mentioning to avoid duplicate work

**Comment by pvliss** [comment]
LOL. Just posted as well

**Comment by pvliss** [comment]
Well, yes the remaining are web, security and client as well some code in aws-containers subgenerator

**Comment by pvliss** [comment]
They are all under the server sub-generator.

The java code can found here: https://github.com/jhipster/generator-jhipster/tree/master/generators/server/templates/src/main/java/package

The Kotlin code should be placed under here: https://github.com/jhipster/jhipster-kotlin/tree/master/generators/server/templates/src/main/kotlin/package

And any related tests to according packages

**Comment by pvliss** [comment]
@amatosg I have finished with the repository package as well and thinking of moving on to either the web or security package. Have you decided if and which one you will pick up as I am going to start tommorow? Thanks

**Comment by amatosg** [comment]
I will give _client_ a try tonight 👍

**Comment by pvliss** [comment]
Cool. I will continue with `web` then. Let me know if you need any help and thanks for helping out

**Comment by pvliss** [comment]
Hello @amatosg. Did you have any time to deal with the client package? Can I be of any help?

**Comment by amatosg** [comment]
wow, a week already? I'm sorry, but I haven't. I changed to a new project and I've been busy. Did you started that already? otherwise I can do it during the week

**Comment by pvliss** [comment]
I have not started it but if you do not have time I would like to do it in order to complete this. Let me know if that's ok with you. Thanks

**Comment by amatosg** [comment]
go ahead, I could take the whole week to finish it at this pace :(

**Comment by pvliss** [comment]
Thanks a lot. Don't worry there will be plenty of things to contribute to. This is just the beginning
