### ISSUE TITLE
Consider using a Koltin linter

### ISSUE THREAD

**Issue by pvliss** [jhipster/jhipster-kotlin#90]
#### Overview of the issue

I think we should consider using a Kotlin linter such as https://github.com/shyiko/ktlint for the generated projects.

#### Motivation for or Use Case

Have properly formatted generated code according to the [official code style](https://kotlinlang.org/docs/reference/coding-conventions.html) and not have to pin-point every little formatting issue at the generator.

[x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Definitely that sounds like a great idea 👍

**Comment by pvliss** [comment]
@sendilkumarn I still have some more changes to commit related to this. Can you please re-open?

**Comment by sendilkumarn** [comment]
Done and assigned it to you. 

I think we can also cut a release after this.

**Comment by pvliss** [comment]
Sure, although I still want to make some changes to some of the classes to use some of the Kotlin features and we need to wait for the JHipster 6.x release as well(at least the beta) don't we?

**Comment by sendilkumarn** [comment]
Yeah I agree, but we will just cut a minor release.

**Comment by pvliss** [comment]
:+1:

**Comment by pvliss** [comment]
I was wrong about this one. I have already merged all changes form my branch into #98, hence closing
